# Setup
title: Eternity-Sky
description: A simple, beautiful, and powerful Jekyll theme for blogs
url: https://Eternity-Sky.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - Eternity-Sky.gemspec

# Optimize Jekyll SEO Tag
twitter:
  username: Eternity-Sky
  card: summary
logo: logo.png
social:
  name: Eternity-Sky
  links:
    - https://github.com/Eternity-Sky
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-M0PKVM9V3E

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Eternity-Sky
  url: https://github.com/Eternity-Sky/
  email: tengyumo666@hotmail.com

gitalk:
  clientID: 'Ov23liAH1r1yD3tBz8CB'
  clientSecret: '8fcc55d81d779b1249765016e17c273ac04515bb'
  repo: 'blog-comments'
  owner: 'Eternity-Sky'
  admin: ['Eternity-Sky']
  distractionFreeMode: false
